post http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###
GET http://localhost:3000/states/
authorization: : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWFOIjoxNzA2NjAxMTI5fQ.5zj396N01wMQ6VXzRDcwynBx-Jic-Zv5YIYv8TE9Tqk

###
GET http://localhost:3000/states/3/
authorization: : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWFOIjoxNzA2NjAxMTI5fQ.5zj396N01wMQ6VXzRDcwynBx-Jic-Zv5YIYv8TE9Tqk


###
POST http://localhost:3000/districts/
Content-Type: application/json
authorization: : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWFOIjoxNzA2NjAxMTI5fQ.5zj396N01wMQ6VXzRDcwynBx-Jic-Zv5YIYv8TE9Tqk


{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###
GET http://localhost:3000/districts/322/
authorization: : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWFOIjoxNzA2NjAxMTI5fQ.5zj396N01wMQ6VXzRDcwynBx-Jic-Zv5YIYv8TE9Tqk


###
DELETE http://localhost:3000/districts/3/
authorization: : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWFOIjoxNzA2NjAxMTI5fQ.5zj396N01wMQ6VXzRDcwynBx-Jic-Zv5YIYv8TE9Tqk


###
Put http://localhost:3000/districts/322/
Content-Type: application/json
authorization: : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWFOIjoxNzA2NjAxMTI5fQ.5zj396N01wMQ6VXzRDcwynBx-Jic-Zv5YIYv8TE9Tqk


{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###
GET http://localhost:3000/states/8/
authorization: : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWFOIjoxNzA2NjAxMTI5fQ.5zj396N01wMQ6VXzRDcwynBx-Jic-Zv5YIYv8TE9Tqk

